INSERT INTO artist(id, name, link) VALUES(0, "Suhaib Attar", "https://www.instagram.com/suhaib_attar/?hl=en");
INSERT INTO artist(id, name, link) VALUES(1, "Axel", "https://www.instagram.com/sed_ghoush/?hl=en");
INSERT INTO artist(id, name, link) VALUES(2, "Yazan Mesmar", "https://www.instagram.com/yazan.mesmar/" );
INSERT INTO artist(id, name, link) VALUES(3, "Suha Sultan", "https://www.instagram.com/paint_ash/" );
INSERT INTO artist(id, name, link) VALUES(4, "Miramar", "https://www.instagram.com/miramar.muhd" );
INSERT INTO artist(id, name, link) VALUES(5, "AWS", "https://www.instagram.com/awsabusalah_/");
INSERT INTO artist(id, name, link) VALUES(6, "Wize One", "https://www.instagram.com/wesamshadid/");
INSERT INTO artist(id, name, link) VALUES(7, "Dhad Store", "https://www.instagram.com/dhadstore/");
INSERT INTO artist(id, name, link) VALUES(8, "Dina Aqel", "https://www.instagram.com/dina_aqel/");
INSERT INTO artist(id, name, link) VALUES(9, "MigTheRobot", "https://www.instagram.com/migtherobot/");
INSERT INTO artist(id, name, link) VALUES(10, "CPTIN", "https://www.instagram.com/aboodgraffiti/");
INSERT INTO artist(id, name, link) VALUES(11, "Yaratun", "https://www.instagram.com/yara.hindawi/");
INSERT INTO artist(id, name, link) VALUES(12, "Yazan Halawani", "https://www.instagram.com/yazanhalwani/");
INSERT INTO artist(id, name, link) VALUES(13, "SINER", "https://www.instagram.com/siner_19/");
INSERT INTO artist(id, name, link) VALUES(14, "Sara Allan", "https://www.instagram.com/inahasara/");
INSERT INTO artist(id, name, link) VALUES(15, "omarsha3", "https://www.instagram.com/omarsha3/");